Для успішного виконання домашки використовуйте документацію [NumPy](https://numpy.org/doc/stable/).

Зверніть увагу на такі методи `numpy`:
* *arange*
* *zeros*
* *ones*
* *full*
* *nonzero*
* *eye*
* *random*
* *sort*
* *sum*
* *min*
* *mean*

In [1]:
import numpy as np

In [2]:
# Завдання 1: Створити масив розміром 3x3 зі значеннями від 0 до 8
# Hints: np.arange
arr1 = np.arange(9).reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# Завдання 2: Створити вектор розміром 10, заповнений нулями
arr2 = np.zeros(10)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Завдання 3: Створити вектор розміром 10, заповнений одиницями
arr3 = np.ones(10)
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# Завдання 4: Створити вектор розміром 10, заповнений значеннями 5
# Hints: np.full
arr4 = np.full(10, 5)
print(arr4)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
# Завдання 5: Створити вектор з числами від 10 до 49
arr5 = np.arange(10, 50)
print(arr5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# Завдання 6: Реверсувати порядок елементів вектора з завдання 5
arr6 = arr5[::-1]
print(arr6)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
# Завдання 7: Створити 9x9 матрицю зі значеннями від 0 до 80
# Hints: np.arange
arr7 = np.arange(81).reshape(9,9)
print(arr7)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [9]:
# Завдання 8: Знайти індекси ненульових елементів вектора [1,2,0,0,4,0]
# Hints: np.nonzero
arr8 = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr8)
print(nonzero_indices)

(array([0, 1, 4], dtype=int64),)


In [10]:
# Завдання 9: Створити одиничну матрицю розміром 3x3
# Hints: np.eye
arr9 = np.eye(3)
print(arr9)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Завдання 10: Створити випадковий вектор розміром 10 та відсортувати його
arr10 = np.random.random(10)
arr10_sorted = np.sort(arr10)

print("Original array:", arr10)
print("Sorted array:", arr10_sorted)

Original array: [0.35842201 0.01233799 0.44954827 0.32142517 0.93335246 0.96166086
 0.65971591 0.35576365 0.07121417 0.8272107 ]
Sorted array: [0.01233799 0.07121417 0.32142517 0.35576365 0.35842201 0.44954827
 0.65971591 0.8272107  0.93335246 0.96166086]


In [12]:
# Завдання 11: Створити матрицю 5x5 з випадковими цілими числами в діапазоні від 0 до 10
arr11 = np.random.randint(0, 11, size=(5, 5))
print(arr11)

[[ 0  9  2  5  4]
 [10  1  7  3  5]
 [ 7  3 10  2  7]
 [ 5 10  2  0 10]
 [ 6  0  2  6  3]]


In [13]:
# Завдання 12: Обчислити суму всіх елементів матриці з завдання 11
arr11_sum = np.sum(arr11)
print(arr11_sum)

119


In [14]:
# Завдання 13: Знайти найменше значення в кожному рядку матриці з завдання 11
arr11_min_row = np.min(arr11, axis=1)
print(arr11_min_row)

[0 1 2 0 0]


In [15]:
# Завдання 14: Обчислити середнє значення кожного стовпця матриці з завдання 11
arr11_mean_col = np.mean(arr11, axis=0)
print(arr11_mean_col)

[5.6 4.6 4.6 3.2 5.8]


In [16]:
# Завдання 15: Створити випадковий вектор розміром 15 та замінити максимальне значення на -1
# Hints: np.argmax
arr15 = np.random.random(15)
print(arr15)

arr15[np.argmax(arr15)] = -1
print(arr15)

[0.50946187 0.69340694 0.72754271 0.88840828 0.06799684 0.74937178
 0.36988839 0.46150914 0.68685091 0.76264769 0.77737684 0.40860946
 0.65063609 0.65465121 0.37388063]
[ 0.50946187  0.69340694  0.72754271 -1.          0.06799684  0.74937178
  0.36988839  0.46150914  0.68685091  0.76264769  0.77737684  0.40860946
  0.65063609  0.65465121  0.37388063]


In [17]:
# Завдання 16: Перетворити випадковий вектор розміром 10 в матрицю розміром 2x5
arr16 = np.random.random(10).reshape(2, 5)
print(arr16)

[[0.18488821 0.2241838  0.16723842 0.59396836 0.06051861]
 [0.8917403  0.88441114 0.39226056 0.34944991 0.13083804]]


In [18]:
# Завдання 17: Знайти середнє значення елементів матриці з завдання 16
arr16_mean = np.mean(arr16)
print(arr16_mean)

0.3879497332213734
