# numpy

In [1]:
import numpy as np

1. Створіть масив NumPy із 10 випадкових цілих чисел. Виконайте наступні операції:
- Знайдіть середнє, медіану та стандартне відхилення масиву.
- Замініть всі парні числа у масиві на 0.

In [2]:
array = np.random.randint(1, 100, 10)
print(array)

[37 90 90 18 38 69 34 31 37 97]


In [3]:
mean = np.mean(array)
median = np.median(array)
std_dev_p = np.std(array)
std_dev_s = np.std(array, ddof=1)

print("Середнє:", mean)
print("Медіана:", median)
print("Некореговане стандартне відхилення:", round(std_dev_p, 2))
print("Кореговане стандартне відхилення:", round(std_dev_s, 2))

Середнє: 54.1
Медіана: 37.5
Некореговане стандартне відхилення: 27.79
Кореговане стандартне відхилення: 29.3


In [4]:
array[array % 2 == 0] = 0
print("Масив після заміни парних чисел на 0:", array)

Масив після заміни парних чисел на 0: [37  0  0  0  0 69  0 31 37 97]


2. Індексація та зрізка в NumPy:
- Створіть 2D масив NumPy (матрицю) розміром (3, 3) із випадковими цілими числами.
- Виведіть перший рядок матриці.
- Виведіть останній стовпець матриці.
- Виведіть діагональні елементи матриці.

In [5]:
matrix = np.random.randint(1, 100, (3, 3))
print(matrix)

[[74 38 62]
 [28 11 38]
 [52 59 87]]


In [6]:
print(matrix[0])

[74 38 62]


In [7]:
print(matrix[:, -1])

[62 38 87]


In [8]:
print(np.diag(matrix))

[74 11 87]


3. Створіть 2D масив NumPy розміром (3, 3) та 1D масив розміром (3,). Використайте broadcasting для додавання 1D масиву до кожного рядка 2D масиву.

In [9]:
array_2d = np.random.randint(1, 100, (3, 3))
print(array_2d)

[[53 57 71]
 [99 92 45]
 [44 47 11]]


In [10]:
array_1d = np.random.randint(1, 100, 3)
print(array_1d)

[83 55  2]


In [11]:
broadcasted_sum = array_2d + array_1d
print(broadcasted_sum)

[[136 112  73]
 [182 147  47]
 [127 102  13]]


4. Створіть 2D масив NumPy розміром (5, 5) з випадковими цілими числами.
- Знайдіть та виведіть всі унікальні елементи у масиві.
- виведіть всі рядки, сума елементів у яких більша за певне значення. (значення оберіть самі)

In [12]:
matrix_5x5 = np.random.randint(1, 100, (5, 5))
print(matrix_5x5)

[[93 44  6 20  4]
 [10 79 84 19 13]
 [55 88 52 92 65]
 [ 4 23 95 52 50]
 [20 69 90 17 41]]


In [13]:
unique_elements = np.unique(matrix_5x5)
print(unique_elements)

[ 4  6 10 13 17 19 20 23 41 44 50 52 55 65 69 79 84 88 90 92 93 95]


In [14]:
threshold_value = 200
rows_with_sum_greater = matrix_5x5[np.sum(matrix_5x5, axis=1) > threshold_value]
print(rows_with_sum_greater)

[[10 79 84 19 13]
 [55 88 52 92 65]
 [ 4 23 95 52 50]
 [20 69 90 17 41]]


5. Створіть 1D масив NumPy, що містить цілі числа від 1 до 20 (включно).
- Використайте оператор shape, щоб перетворити 1D масив у 2D масив розміром (4, 5). Переконайтеся, що отриманий перетворений масив має бажаний розмір.

In [15]:
array_1d = np.arange(1, 21)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
array_2d = array_1d.reshape((4, 5))
print(array_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
array_2d.shape

(4, 5)

# pandas

In [18]:
import pandas as pd

1. Створіть DataFrame Pandas із щонайменше 5 рядками та 3 стовпцями. Стовпці можуть представляти різні атрибути (наприклад, Ім'я, Вік, Місто).

In [19]:
data = {'Name': ['Alexander', 'Maria', 'Ivan', 'Elena', 'Victor'],
        'Age': [28, 22, 19, 32, 45],
        'City': ['Kyiv', 'Lviv', 'Odesa', 'Kharkiv', 'Dnipro']}

df = pd.DataFrame(data)
df

Name  Age     City
0  Alexander   28     Kyiv
1      Maria   22     Lviv
2       Ivan   19    Odesa
3      Elena   32  Kharkiv
4     Victor   45   Dnipro

2. Додайте новий стовпець до DataFrame, який представляє числове значення.

In [20]:
df['Salary'] = [30000, 25000, 20000, 32000, 40000]
df

Name  Age     City  Salary
0  Alexander   28     Kyiv   30000
1      Maria   22     Lviv   25000
2       Ivan   19    Odesa   20000
3      Elena   32  Kharkiv   32000
4     Victor   45   Dnipro   40000

3. Відфільтруйте DataFrame, щоб показати лише рядки, де числове значення більше певного порогу (ви можете визначити поріг).

In [21]:
filtered_df = df[df['Salary'] > 30000]
filtered_df

Name  Age     City  Salary
3   Elena   32  Kharkiv   32000
4  Victor   45   Dnipro   40000

4. Завантажте набір даних за допомогою Pandas (ви можете використовувати будь-який набір даних у форматі CSV або wine.csv).

In [22]:
data = pd.read_csv('wine.csv')

5. Відобразіть перші 5 рядків набору даних.

In [23]:
data.head(5)

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

6. Розрахуйте та виведіть загальну статистику для числових стовпців у наборі даних.

In [24]:
summary_statistics = data.describe()
summary_statistics

Wine     Alcohol  Malic.acid         Ash         Acl          Mg  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

          Phenols  Flavanoids  Nonflavanoid.phenols     Proanth   Color.int  \
count  178.000000  178.000000            178.000000  178.000000  178.000000   
mean     2.295112    2.029270              0.361854    1.590899    5.058090   
std      0.625851    0.998859              0.124453    0.572359    2.318286   
min      0.980000    0.340000              0.130000    0.410000    1.280000   
25%      1.742500    1.205000              0.270000    1.250000    3.220000   
50%      2.355000    2.135000              0.340000    1.555000    4.690000   
75%      2.800000    2.875000              0.437500    1.950000    6.200000   
max      3.880000    5.080000              0.660000    3.580000   13.000000   

              Hue          OD      Proline  
count  178.000000  178.000000   178.000000  
mean     0.957449    2.611685   746.893258  
std      0.228572    0.709990   314.907474  
min      0.480000    1.270000   278.000000  
25%      0.782500    1.937500   500.500000  
50%      0.965000    2.780000   673.500000  
75%      1.120000    3.170000   985.000000  
max      1.710000    4.000000  1680.000000

7. Знайдіть та виведіть унікальні значення у категорійному стовпці.

In [28]:
data['Wine'] = data['Wine'].astype('category')
print(data['Wine'].unique())

[1, 2, 3]
Categories (3, int64): [1, 2, 3]
